# Generated by Django 2.2 on 2023-03-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_webapp', '0003_anime2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
